name: devotion
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.3.0
  video_player:
  json_to_model: ^1.3.13
  audio_service: ^0.16.1
  just_audio: ^0.6.9
  scoped_model: ^1.1.0
  image_picker: ^0.6.6+5
  animations: ^1.1.0
  http: ^0.12.1  
  flutter_secure_storage: ^3.3.5
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  meta: ^1.1.6
  equatable: ^1.0.0
  rxdart: ^0.24.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/CustomIcons.ttf
  assets:
    - images/athens.jpg
    - images/avatar1.jpg
    - images/avatar2.jpg
    - images/photo.png
    - images/music_thumb.png
    - images/map.png
    - images/church.jpg
    - images/devotional.jpg
